import React, { createContext, useContext, useState, ReactNode } from 'react';

export interface LanguageContextProps {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Header Navigation
    'header.why-aptos': 'Why Aptos',
    'header.advantages': 'Advantages',
    'header.presentation': 'Presentation',
    'header.learn-more': 'Learn more',
    
    // Navigation
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    
    // Hero Section
    'hero.title': 'The future of retirement is here',
    'hero.subtitle': 'Join the blockchain revolution that will transform how we save for retirement. Transparent, secure, and profitable.',
    'hero.cta': 'Start your journey',
    'hero.learn-more': 'Learn more',
    
    // Dashboard
    'dashboard.welcome': 'Welcome to your AFJP dashboard',
    'dashboard.title': 'AFJP dashboard',
    'dashboard.balance': 'Your balance',
    'dashboard.afjp-tokens': 'AFJP Tokens',
    'dashboard.usd-value': 'USD value',
    'dashboard.monthly-contribution': 'Monthly contribution',
    'dashboard.total-contributed': 'Total contributed',
    'dashboard.projected-retirement': 'Projected at retirement',
    'dashboard.recent-activity': 'Recent activity',
    'dashboard.news-updates': 'News & updates',
    'dashboard.contribute-now': 'Contribute now',
    'dashboard.retirement-tokens': 'Retirement tokens',
    'dashboard.total-estimated-value': 'Total estimated value',
    'dashboard.per-token': 'per token',
    'dashboard.contribute': 'Contribute',
    'dashboard.contribute-desc': 'Add funds to your retirement account',
    'dashboard.submarket': 'Token market',
    'dashboard.submarket-desc': 'Buy, sell and exchange tokens',
    'dashboard.benefits': 'Benefits',
    'dashboard.benefits-desc': 'Access your retirement benefits',
    'dashboard.recent-transactions': 'Recent transactions',
    'dashboard.fund-news': 'Fund news',
    
    // Contribute
    'contribute.title': 'Contribute to your retirement',
    'contribute.description': 'Secure your future with our easy contribution options',
    'contribute.next-payment': 'September 2025',
    'contribute.months': 'Months paid',
    'contribute.years': 'Years paid',
    'contribute.tokens': 'AFJP Tokens',
    'contribute.total': 'in total',
    'contribute.growth': 'Token growth',
    'contribute.beginning': 'Since you joined',
    'contribute.next': 'Next contribution',
    'contribute.next-month': 'Next month to pay',
    'contribute.pending': 'Pending monthly contributions',
    'contribute.pending-years': 'pending years',
    'contribute.progress': 'Progress to retirement',
    'contribute.age': 'Current age:',
    'contribute.agey': 'years',
    'contribute.ageof': 'Retirement age:',
    'contribute.completed': ' years completed',
    'contribute.rest': ' years remaining',
    'contribute.transactions': 'Contribution history',
    'contribute.year': 'Year',
    'contribute.month': 'Months Paid',
    'contribute.amount': 'Total Amount',
    'contribute.status': 'Status',
    'contribute.new': 'Make New Contribution',
    'contribute.currency': 'Currency',
    'contribute.contribution': 'Contribution Amount',
    'contribute.receive': 'You will receive',
    'contribute.afjp': 'AFJP Tokens',
    'contribute.confirm': 'Confirm Contribution',
    'contribute.add': 'This contribution will be added to your retirement contribution history',
    'contribute.rate': 'Conversion Rate: ',
    // Tabs
    'tabs.overview': 'Overview',
    'tabs.contribute': 'Contribute',
    'tabs.tokenburn': 'Token burn',
    'tabs.marketplace': 'Marketplace',
    'tabs.realestate': 'Real estate',
    'tabs.tourism': 'Tourism',
    'tabs.benefits': 'Benefits',
    
    // Marketplace
    'marketplace.title': 'Token marketplace',
    'marketplace.subtitle': 'Buy, sell, exchange AFJP tokens and request loans with tokenized collateral',
    'marketplace.buy-tokens': 'Buy tokens',
    'marketplace.sell-tokens': 'Sell tokens',
    'marketplace.simulation': 'SIMULATION',
    'marketplace.buy-confirmation': 'Buy {tokens} tokens for ${cost} USD',
    'marketplace.sell-confirmation': 'Sell {tokens} tokens for ${value} USD',
    'marketplace.exchange': 'Exchange',
    'marketplace.credit': 'Credit',

    // Tourism
    'tourism.title': 'JUVENTUD Tourism',
    'tourism.subtitle': 'Discover unique destinations in Argentina and worldwide with exclusive discounts for affiliates. Pay with your JUVENTUD tokens and enjoy unforgettable experiences.', 
    'tourism.payment': 'Token payment',
    'tourism.payment-desc': 'Use JUVENTUD to get discounts',
    'tourism.affiliates': 'Affiliates only',
    'tourism.affiliates-desc': 'Exclusive benefits for members',
    'tourism.argentina': 'Argentina',
    'tourism.argentina-desc': 'Destinations across the country',
    'tourism.worldwide': 'Worldwide',
    'tourism.worldwide-desc': 'International destinations',
    'tourism.explore': 'Explore the natural beauty of our country',
    'tourism.destinations': 'Destinations in Argentina',
    'tourism.international': 'International destinations',
    'tourism.discover': 'Discover the world with JUVENTUD',
    'tourism.book': 'Book Cabin',
    'tourism.checkin': 'Check-in',
    'tourism.checkout': 'Check-out',
    'tourism.guests': 'Guests',
    'tourism.max': 'Maximum',
    'tourism.people': 'people',

    // Token Exchange (replacing Token Burn)
    'tokenexchange.title': 'Token exchange',
    'tokenexchange.subtitle': 'Exchange your AFJP tokens for JUVENTUD tokens to access premium benefits',
    'tokenexchange.exchange-title': 'Exchange tokens',
    'tokenexchange.exchange-description': 'Exchange AFJP tokens for JUVENTUD tokens at a fixed rate',
    'tokenexchange.afjp-balance': 'AFJP balance',
    'tokenexchange.juventud-balance': 'JUVENTUD balance',
    'tokenexchange.juventud-tokens': 'JUVENTUD',
    'tokenexchange.amount-to-exchange': 'Amount to exchange (AFJP)',
    'tokenexchange.rate-info': 'Exchange Rate: {rate} AFJP = 1 JUVENTUD',
    'tokenexchange.you-will-receive': 'You will receive',
    'tokenexchange.confirm-exchange': 'Confirm exchange',
    'tokenexchange.exchange-warning': '⚠️ Please verify the exchange details',
    'tokenexchange.simulation': 'SIMULATION',
    'tokenexchange.exchange-confirmation': 'Exchange {afjp} AFJP tokens to receive {juventud} JUVENTUD tokens',
    'tokenexchange.benefits-title': 'JUVENTUD Token benefits',
    'tokenexchange.benefits-description': 'Unlock exclusive advantages with JUVENTUD tokens',
    'tokenexchange.benefit-1': 'Preferential rental rates in our real estate portfolio',
    'tokenexchange.benefit-2': 'Priority access to new property developments',
    'tokenexchange.benefit-3': 'Enhanced voting rights in governance decisions',
    
    // Inheritance Section
    'inheritance.title': 'Token inheritance',
    'inheritance.beneficiaries-config': 'Beneficiaries configuration',
    'inheritance.configured-desc': 'Your inheritance is configured and ready',
    'inheritance.not-configured-desc': 'Your inheritance needs to be configured',
    'inheritance.config-status': 'Configuration status',
    'inheritance.completed': 'Completed',
    'inheritance.designated-beneficiaries': 'Designated beneficiaries',
    'inheritance.primary-beneficiary': 'Primary beneficiary',
    'inheritance.secondary-beneficiary': 'Secondary beneficiary',
    'inheritance.last-update': 'Last updated:',
    'inheritance.how-it-works': 'How it works',
    'inheritance.description': 'Our token inheritance system ensures your AFJP tokens are safely transferred to your beneficiaries in case of unexpected events, following blockchain security protocols.',
    'inheritance.step1': 'Designate your beneficiaries and assign percentages of your token portfolio',
    'inheritance.step2': 'Submit legal documentation and identity verification for each beneficiary',
    'inheritance.step3': 'The system creates a secure smart contract with your inheritance instructions',
    'inheritance.step4': 'In case of inheritance activation, tokens are automatically distributed according to your wishes',
    'inheritance.modify-beneficiaries': 'Modify beneficiaries',
    'inheritance.add-documentation': 'Add documentation',
    'inheritance.not-configured-note': 'Secure your family\'s future by configuring your token inheritance plan',
    'inheritance.configure-beneficiaries': 'Configure beneficiaries',
    
    // Health Benefits Section
    'health.header': 'Exclusive Benefits',
    'health.subtitle': 'As an AFJP Cripto affiliate, you access multiple additional benefits to your retirement.',
    'health.benefit-a': 'Real Estate',
    'health.benefit-a-title': '25%',
    'health.benefit-a-subtitle': 'Discount on rental rates in funding properties',
    'health.benefit-a-title-b': 'Priority',
    'health.benefit-a-subtitle-b': 'Early access to new real estate developments',
    'health.benefit-a-title-c': 'Financing',
    'health.benefit-a-subtitle-c': 'Special financing options for purchasing properties',
    'health.benefit-a-cta': 'See properties',
    'health.benefit-b': 'Health',
    'health.benefit-b-title': '30%',
    'health.benefit-b-subtitle': 'Discount on medicines at partner pharmacies',
    'health.benefit-b-title-b': '20%',
    'health.benefit-b-subtitle-b': 'Discount on medical consultations with specialists',
    'health.benefit-b-title-c': 'Free',
    'health.benefit-b-subtitle-c': 'Annual general health check-up',
    'health.benefit-b-cta': 'View pharmacies',
    'health.benefit-c': 'Inheritance',
    'health.benefit-c-title': '100%',
    'health.benefit-c-subtitle': 'Tokens transferred to your beneficiaries',
    'health.benefit-c-title-b': 'Simple',
    'health.benefit-c-subtitle-b': 'Process managed via smart contracts',
    'health.benefit-c-title-c': 'Secure',
    'health.benefit-c-subtitle-c': 'No traditional legal paperwork',
    'health.benefit-c-cta': 'Assign Beneficiaries',
    'health.benefit-d': 'Tokens',
    'health.benefit-d-title': 'Dividends',
    'health.benefit-d-subtitle': 'Participation in funding profits',
    'health.benefit-d-title-b': 'Liquidity',
    'health.benefit-d-subtitle-b': 'Buy and sell in the internal submarket',
    'health.benefit-d-title-c': 'Staking',
    'health.benefit-d-subtitle-c': 'Additional rewards for holding tokens',
    'health.benefit-d-cta': 'Go to Market',
    'health.simulator-title': 'Health discount simulator',
    'health.medicine-price': 'Medicine price (ARS)',
    'health.token-balance': 'JUVENTUD Token balance',
    'health.more-tokens-desc': 'More tokens provide additional discount (up to',
    'health.base-discount': 'Base discount',
    'health.additional-discount': 'Additional discount',
    'health.total-discount': 'Total discount',
    'health.original-price': 'Original price',
    'health.applied-discount': 'Applied discount',
    'health.final-price': 'Final price',
    'health.simulator-note': 'This is a simulation. Actual discounts may vary based on pharmacy partnerships and availability.',

    
    // Pitch Section
    'pitch.title': 'Why AFJP Cripto will revolutionize retirement',
    'pitch.subtitle': 'We are not just another retirement fund. We are the solution the world needs.',
    'pitch.point1.title': 'Unprecedented efficiency and transparency',
    'pitch.point1.description': 'We use blockchain technology to eliminate bureaucracy, opacity, and unnecessary costs. Every contribution, every investment, every transaction is immutable and auditable, maximizing returns for our affiliates and the company\'s profitability.',
    'pitch.point2.title': 'Real wealth generation',
    'pitch.point2.description': 'We invest in real, tokenized assets, primarily real estate, to protect capital from inflation and grow it robustly. Our affiliates not only accumulate funds but have the security that their money is working for them, not being eroded.',
    'pitch.point3.title': 'Purpose-driven business model ($AFJP and $JUVENTUD)',
    'pitch.point3.description': 'Our tokenomics is a brilliant growth strategy. Affiliates burn $AFJP to obtain $JUVENTUD, which grants them access to preferential rents in our growing real estate portfolio. This not only drives demand for our main token but also guarantees occupancy of our real estate assets, optimizing our revenue and attracting new generations with a real, tangible housing solution.',
    'pitch.execution.title': 'Our execution plan and team strength',
    'pitch.execution.description': 'We know that a vision of this magnitude requires flawless execution. For that, we will seek your support.',
    
    // Transactions
    'transactions.deposit': 'Deposit',
    'transactions.purchase': 'Purchase',
    'transactions.sale': 'Sale',
    'transactions.reward': 'Reward',
    'transactions.no-recent': 'No recent transactions',
    
    // News
    'news.new-property': 'New property added to portfolio',
    'news.new-property-desc': 'Luxury apartment complex in downtown area now available for investment',
    'news.token-high': 'AFJP Token reaches new high',
    'news.token-high-desc': 'Token value increased 5% this month due to strong portfolio performance',
    'news.health-benefits': 'New health benefits available',
    'news.health-benefits-desc': 'Premium health insurance now available for all JUVENTUD token holders',
    'news.no-recent': 'No recent news',
    
    // Real Estate
    'realestate.title': 'Real estate portfolio',
    'realestate.description': 'Discover our exclusive real estate projects available to AFJP Cripto affiliates. Access properties with special benefits and payment options using your tokens.',
    'realestate.exclusive-benefits': 'Exclusive benefits for affiliates',
    'realestate.as-affiliate': 'As an AFJP Cripto affiliate, you have access to special benefits in our real estate portfolio',
    'realestate.exclusive': 'Exclusive',
    'realestate.discount-25': '25% Discount',
    'realestate.discount-desc': 'Special discount on rental rates for all AFJP Cripto affiliates',
    'realestate.juventud-25': 'Pay with JUVENTUD',
    'realestate.juventud-desc': 'Rent properties paying directly with JUVENTUD tokens',
    'realestate.ladrillo-25': 'Buy with LADRILLO',
    'realestate.ladrillo-desc': 'Buy propertis using LADRILLO tokens for real estate investments',
    'realestate.special-financing': 'Special financing',
    'realestate.financing-desc': 'Flexible payment options and preferential terms',
    'realestate.available-projects': 'Available projects',
    'realestate.torres-puerto': 'Aptos Towers',
    'realestate.torres-location': 'Puerto Madero, Buenos Aires',
    'realestate.apartments': 'Apartments',
    'realestate.under-construction': 'Under construction',
    'realestate.completed': 'Completed',
    'realestate.pre-sale': 'Pre-sale',
    'realestate.express-interest': 'Express your interest',
    'realestate.interest-form-desc': 'Leave your information and we will contact you with personalized offers.',
    'realestate.projects': 'Projects',
    'realestate.projects-desc': 'Invest with LADRILLO tokens in future real estate projects and support their development from the beginning',
    'realestate.investment': 'Investment in Future Projects',
    'realestate.investment-desc': 'Use your LADRILLO tokens to finance and support the development of new real estate projects',
    'realestate.finance': 'Direct Financing',
    'realestate.finance-desc': 'Contribute directly to project development using LADRILLO tokens',
    'realestate.returns': 'Attractive Returns',
    'realestate.returns-desc': 'Earn estimated returns between 10% and 15% annually upon project completion',
    'realestate.early': 'Early Participation',
    'realestate.early-desc': 'Access investment opportunities before the general market',

    // Form translations
    'form.name-required': 'Name is required',
    'form.invalid-email': 'Please enter a valid email',
    'form.invalid-phone': 'Please enter a valid phone number',
    'form.select-interest': 'Please select your interest',
    'form.sent-title': 'Form sent!',
    'form.sent-desc': 'We will contact you soon with more information.',
    'form.full-name': 'Full name',
    'form.your-name': 'Your name',
    'form.email': 'Email',
    'form.phone': 'Phone',
    'form.interested-in': 'I am interested in:',
    'form.rent-property': 'Renting a property',
    'form.buy-property': 'Buying a property',
    'form.receive-info': 'Receiving information only',
    'form.additional-message': 'Additional message (Optional)',
    'form.additional-placeholder': 'Tell us about your specific needs or preferences...',
    'form.send-request': 'Send request',
    
    // Footer
    'footer.links': 'Quick Links',
    'footer.resources': 'Resources',
    'footer.official-aptos': 'Official Aptos',
    'footer.documentation': 'Documentation',
    'footer.explorer': 'Block Explorer',
    'footer.rights': '© 2025 AFJP Cripto. All rights reserved.',
    
    // Why Aptos Section
    'why-aptos.title': 'Why choose',
    'why-aptos.subtitle': 'Discover the advantages of building our retirement fund on the most advanced blockchain ecosystem',
    'why-aptos.interoperability': 'Interoperability',
    'why-aptos.interoperability-desc': 'Connect with multiple blockchains and financial systems seamlessly',
    'why-aptos.scalability': 'Scalability',
    'why-aptos.scalability-desc': 'Process thousands of transactions per second with minimal fees',
    'why-aptos.security': 'Security',
    'why-aptos.security-desc': 'Secutity model featuring cryptography',
    'why-aptos.governance': 'DAO governance',
    'why-aptos.governance-desc': 'Democratic governance system for protocol upgrades and decisions',
    
    // Advantages Section
    'advantages.title': 'Competitive Advantages',
    'advantages.subtitle': 'Why AFJP Cripto is the best choice for your blockchain-based retirement',
    'advantages.dedicated-parachain': 'Optimised blockchain',
    'advantages.dedicated-desc': 'Storing photos and videos costs less thanks to Aptos',
    'advantages.tokenized-assets': 'Tokenized Real Assets',
    'advantages.tokenized-desc': 'Real estate and traditional assets represented as blockchain tokens',
    'advantages.institutional-security': 'Institutional Security',
    'advantages.institutional-desc': 'Bank-level security with blockchain transparency',
    'advantages.continuous-evolution': 'Continuous Evolution',
    'advantages.continuous-desc': 'Regular updates and improvements without service interruption',
    'advantages.defi-ecosystem': 'DeFi Ecosystem',
    'advantages.defi-desc': 'Access to decentralized finance tools and yield opportunities',
    'advantages.long-term-resistance': 'Long-term resistance',
    'advantages.long-term-desc': 'Built to last decades with evolving technology standards',
  },
  es: {
    // Header Navigation
    'header.why-aptos': 'Por qué Aptos',
    'header.advantages': 'Ventajas',
    'header.presentation': 'Presentación',
    'header.learn-more': 'Saber Más',
    
    // Navigation
    'nav.home': 'Inicio',
    'nav.dashboard': 'Panel',
    'nav.about': 'Acerca de',
    'nav.contact': 'Contacto',
    
    // Hero Section
    'hero.title': 'El futuro de la jubilación está acá',
    'hero.subtitle': 'Únete a la revolución blockchain que transformará cómo ahorramos para la jubilación. Transparente, seguro y rentable.',
    'hero.cta': 'Comienza Tu viaje',
    'hero.learn-more': 'Saber más',
    
    // Dashboard
    'dashboard.welcome': 'Bienvenido a tu panel AFJP',
    'dashboard.title': 'Panel AFJP',
    'dashboard.balance': 'Tu saldo',
    'dashboard.afjp-tokens': 'Tokens AFJP',
    'dashboard.usd-value': 'Valor en USD',
    'dashboard.monthly-contribution': 'Contribución mensual',
    'dashboard.total-contributed': 'Total contribuido',
    'dashboard.projected-retirement': 'Proyectado al retiro',
    'dashboard.recent-activity': 'Actividad reciente',
    'dashboard.news-updates': 'Noticias y actualizaciones',
    'dashboard.contribute-now': 'Contribuir ahora',
    'dashboard.retirement-tokens': 'Tokens de jubilación',
    'dashboard.total-estimated-value': 'Valor total estimado',
    'dashboard.per-token': 'por token',
    'dashboard.contribute': 'Contribuir',
    'dashboard.contribute-desc': 'Agrega fondos a tu cuenta de jubilación',
    'dashboard.submarket': 'Mercado de Tokens',
    'dashboard.submarket-desc': 'Compra, vende e intercambia tokens',
    'dashboard.benefits': 'Beneficios',
    'dashboard.benefits-desc': 'Accede a tus beneficios de jubilación',
    'dashboard.recent-transactions': 'Transacciones recientes',
    'dashboard.fund-news': 'Noticias del fondo',

    // Contribute
    'contribute.title': 'Contribuye a tu jubilación',
    'contribute.description': 'Asegura tu futuro con nuestras fáciles opciones de contribución',
    'contribute.next-payment': 'Septiembre 2025',
    'contribute.months': 'Meses pagados',
    'contribute.years': 'Años pagados',
    'contribute.tokens': 'Tokens AFJP',
    'contribute.total': 'en total',
    'contribute.growth': 'Crecimiento de Token',
    'contribute.beginning': 'desde que te uniste',
    'contribute.next': 'Próxima contribución',
    'contribute.next-month': 'Próximo mes a pagar',
    'contribute.pending': 'Contribuciones mensuales pendientes',
    'contribute.pending-years': 'años pendientes',
    'contribute.progress': 'Progreso hacia la jubilación',
    'contribute.age': 'Edad actual:',
    'contribute.agey': 'años',
    'contribute.ageof': 'Edad de jubilación:',
    'contribute.completed': ' años completados',
    'contribute.rest': ' años restantes',
    'contribute.transactions': 'Historial de Aportes',
    'contribute.year': 'Año',
    'contribute.month': 'Meses Pagados',
    'contribute.amount': 'Monto Total',
    'contribute.status': 'Estado',
    'contribute.new': 'Realizar Nuevo Aporte',
    'contribute.currency': 'Moneda',
    'contribute.contribution': 'Monto del Aporte',
    'contribute.receive': 'Recibirás',
    'contribute.afjp': 'Tokens AFJP',
    'contribute.confirm': 'Confirmar Aporte',
    'contribute.add': 'Este aporte se sumará a tu historial de contribuciones para la jubilación',
    'contribute.rate': 'Tasa de conversión: ',

    // Tabs
    'tabs.overview': 'Resumen',
    'tabs.contribute': 'Contribuir',
    'tabs.tokenburn': 'Quemar Tokens',
    'tabs.marketplace': 'Mercado',
    'tabs.realestate': 'Inmuebles',
    'tabs.tourism': 'Turismo',
    'tabs.benefits': 'Beneficios',
    
    // Marketplace
    'marketplace.title': 'Mercado de Tokens',
    'marketplace.subtitle': 'Compra, vende, intercambia tokens AFJP y solicita créditos con garantía tokenizada',
    'marketplace.buy-tokens': 'Comprar Tokens',
    'marketplace.sell-tokens': 'Vender Tokens',
    'marketplace.simulation': 'SIMULACIÓN',
    'marketplace.buy-confirmation': 'Comprar {tokens} tokens por ${cost} USD',
    'marketplace.sell-confirmation': 'Vender {tokens} tokens por ${value} USD',
    'marketplace.exchange': 'Intercambio',
    'marketplace.credit': 'Crédito',

    // Tourism
    'tourism.title': 'Turismo JUVENTUD',
    'tourism.subtitle': 'Descubre destinos únicos en Argentina y el mundo con descuentos exclusivos para afiliados. Paga con tus tokens JUVENTUD y disfruta de experiencias inolvidables.',
    'tourism.payment': 'Pago con Tokens',
    'tourism.payment-desc': 'Usa JUVENTUD para obtener descuentos',
    'tourism.affiliates': 'Solo Afiliados',
    'tourism.affiliates-desc': 'Beneficios exclusivos para miembros',
    'tourism.argentina': 'Argentina',
    'tourism.argentina-desc': 'Destinos en todo el país',
    'tourism.worldwide': 'Mundial',
    'tourism.worldwide-desc': 'Destinos internacionales',
    'tourism.explore': 'Explora la belleza natural de nuestro país',
    'tourism.destinations': 'Destinos en Argentina',
    'tourism.international': 'Destinos Internacionales',
    'tourism.discover': 'Descubre el mundo con JUVENTUD',
    'tourism.book': 'Reservar Cabaña',
    'tourism.checkin': 'Entrada',
    'tourism.checkout': 'Salida',
    'tourism.guests': 'Huéspedes',
    'tourism.max': 'Máximo',
    'tourism.people': 'personas',

    // Token Exchange (replacing Token Burn)
    'tokenexchange.title': 'Intercambio de Tokens',
    'tokenexchange.subtitle': 'Intercambia tus tokens AFJP por tokens JUVENTUD para acceder a beneficios premium',
    'tokenexchange.exchange-title': 'Intercambiar Tokens',
    'tokenexchange.exchange-description': 'Intercambia tokens AFJP por tokens JUVENTUD a una tasa fija',
    'tokenexchange.afjp-balance': 'Saldo AFJP',
    'tokenexchange.juventud-balance': 'Saldo JUVENTUD',
    'tokenexchange.juventud-tokens': 'JUVENTUD',
    'tokenexchange.amount-to-exchange': 'Cantidad a Intercambiar (AFJP)',
    'tokenexchange.rate-info': 'Tasa de Cambio: {rate} AFJP = 1 JUVENTUD',
    'tokenexchange.you-will-receive': 'Recibirás',
    'tokenexchange.confirm-exchange': 'Confirmar Intercambio',
    'tokenexchange.exchange-warning': '⚠️ Por favor verifica los detalles del intercambio',
    'tokenexchange.simulation': 'SIMULACIÓN',
    'tokenexchange.exchange-confirmation': 'Intercambiar {afjp} tokens AFJP para recibir {juventud} tokens JUVENTUD',
    'tokenexchange.benefits-title': 'Beneficios del Token JUVENTUD',
    'tokenexchange.benefits-description': 'Desbloquea ventajas exclusivas con tokens JUVENTUD',
    'tokenexchange.benefit-1': 'Tarifas preferenciales de alquiler en nuestro portafolio inmobiliario',
    'tokenexchange.benefit-2': 'Acceso prioritario a nuevos desarrollos inmobiliarios',
    'tokenexchange.benefit-3': 'Derechos de voto mejorados en decisiones de gobernanza',
    
    // Inheritance Section
    'inheritance.title': 'Herencia de Tokens',
    'inheritance.beneficiaries-config': 'Configuración de beneficiarios',
    'inheritance.configured-desc': 'Tu herencia está configurada y lista',
    'inheritance.not-configured-desc': 'Tu herencia necesita ser configurada',
    'inheritance.config-status': 'Estado de configuración',
    'inheritance.completed': 'Completado',
    'inheritance.designated-beneficiaries': 'Beneficiarios designados',
    'inheritance.primary-beneficiary': 'Beneficiario principal',
    'inheritance.secondary-beneficiary': 'Beneficiario secundario',
    'inheritance.last-update': 'Última actualización:',
    'inheritance.how-it-works': 'Cómo funciona',
    'inheritance.description': 'Nuestro sistema de herencia de tokens asegura que tus tokens AFJP sean transferidos de forma segura a tus beneficiarios en caso de eventos inesperados, siguiendo protocolos de seguridad blockchain.',
    'inheritance.step1': 'Designa a tus beneficiarios y asigna porcentajes de tu portafolio de tokens',
    'inheritance.step2': 'Presenta documentación legal y verificación de identidad para cada beneficiario',
    'inheritance.step3': 'El sistema crea un contrato inteligente seguro con tus instrucciones de herencia',
    'inheritance.step4': 'En caso de activación de herencia, los tokens se distribuyen automáticamente según tus deseos',
    'inheritance.modify-beneficiaries': 'Modificar beneficiarios',
    'inheritance.add-documentation': 'Agregar documentación',
    'inheritance.not-configured-note': 'Asegura el futuro de tu familia configurando tu plan de herencia de tokens',
    'inheritance.configure-beneficiaries': 'Configurar beneficiarios',
    
    // Health Benefits Section
    'health.header': 'Beneficios Exclusivos',
    'health.subtitle': 'Como afiliado de AFJP Cripto, accedes a múltiples beneficios adicionales a tu jubilación.',
    'health.benefit-a': 'Inmobiliarios',
    'health.benefit-a-title': '25%',
    'health.benefit-a-subtitle': 'Descuento en alquileres de propiedades de fondo',
    'health.benefit-a-title-b': 'Prioridad',
    'health.benefit-a-subtitle-b': 'Acceso anticipado a nuevos desarrollos inmobiliarios',
    'health.benefit-a-title-c': 'Financiación',
    'health.benefit-a-subtitle-c': 'Planes de pago especiales para compra de propiedades',
    'health.benefit-a-cta': 'Ver Propiedades',
    'health.benefit-b': 'Salud',
    'health.benefit-b-title': '30%',
    'health.benefit-b-subtitle': 'Descuento en medicamentos en farmacias afiliadas',
    'health.benefit-b-title-b': '20%',
    'health.benefit-b-subtitle-b': 'Descuento en consultas médicas con especialistas',
    'health.benefit-b-title-c': 'Gratis',
    'health.benefit-b-subtitle-c': 'Chequeo médico anual preventivo',
    'health.benefit-b-cta': 'Ver Farmacias',
    'health.benefit-c': 'Herencia',
    'health.benefit-c-title': '100%',
    'health.benefit-c-subtitle': 'Transferencia de tokens a beneficiarios designados',
    'health.benefit-c-title-b': 'Simple',
    'health.benefit-c-subtitle-b': 'Proceso automatizado mediante smart contracts',
    'health.benefit-c-title-c': 'Seguro',
    'health.benefit-c-subtitle-c': 'Sin trámites legales tradicionales',
    'health.benefit-c-cta': 'Designar Beneficiarios',
    'health.benefit-d': 'Tokens',
    'health.benefit-d-title': 'Dividendos',
    'health.benefit-d-subtitle': 'Participación en ganancias de fondo',
    'health.benefit-d-title-b': 'Liquidez',
    'health.benefit-d-subtitle-b': 'Compra y venta en el submercado interno',
    'health.benefit-d-title-c': 'Staking',
    'health.benefit-d-subtitle-c': 'Recompensas adicionales por mantener tokens',
    'health.benefit-d-cta': 'Ir al Mercado',
    'health.simulator-title': 'Simulador de descuentos en salud',
    'health.medicine-price': 'Precio del medicamento (ARS)',
    'health.token-balance': 'Saldo de Tokens JUVENTUD',
    'health.more-tokens-desc': 'Más tokens proporcionan descuento adicional (hasta',
    'health.base-discount': 'Descuento Base',
    'health.additional-discount': 'Descuento adicional',
    'health.total-discount': 'Descuento total',
    'health.original-price': 'Precio original',
    'health.applied-discount': 'Descuento aplicado',
    'health.final-price': 'Precio final',
    'health.simulator-note': 'Esta es una simulación. Los descuentos reales pueden variar según las alianzas con farmacias y disponibilidad.',
    
    // Pitch Section
    'pitch.title': 'Why AFJP Cripto will revolutionize retirement',
    'pitch.subtitle': 'We are not just another retirement fund. We are the solution the world needs.',
    'pitch.point1.title': 'Unprecedented efficiency and transparency',
    'pitch.point1.description': 'We use blockchain technology to eliminate bureaucracy, opacity, and unnecessary costs. Every contribution, every investment, every transaction is immutable and auditable, maximizing returns for our affiliates and the company\'s profitability.',
    'pitch.point2.title': 'Real wealth generation',
    'pitch.point2.description': 'We invest in real, tokenized assets, primarily real estate, to protect capital from inflation and grow it robustly. Our affiliates not only accumulate funds but have the security that their money is working for them, not being eroded.',
    'pitch.point3.title': 'Purpose-Driven business model ($AFJP and $JUVENTUD)',
    'pitch.point3.description': 'Our tokenomics is a brilliant growth strategy. Affiliates burn $AFJP to obtain $JUVENTUD, which grants them access to preferential rents in our growing real estate portfolio. This not only drives demand for our main token but also guarantees occupancy of our real estate assets, optimizing our revenue and attracting new generations with a real, tangible housing solution.',
    'pitch.execution.title': 'Our execution plan and team strength',
    'pitch.execution.description': 'We know that a vision of this magnitude requires flawless execution. For that, we will seek your support.',
    
    // Transactions
    'transactions.deposit': 'Depósito',
    'transactions.purchase': 'Compra',
    'transactions.sale': 'Venta',
    'transactions.reward': 'Recompensa',
    'transactions.no-recent': 'No hay transacciones recientes',
    
    // News
    'news.new-property': 'Nueva propiedad agregada al portafolio',
    'news.new-property-desc': 'Complejo de apartamentos de lujo en el centro ahora disponible para inversión',
    'news.token-high': 'Token AFJP Cripto alcanza nuevo Máximo',
    'news.token-high-desc': 'El valor del token aumenta 5% este mes debido al fuerte rendimiento del portafolio',
    'news.health-benefits': 'Nuevos beneficios de salud disponibles',
    'news.health-benefits-desc': 'Seguro de salud premium ahora disponible para todos los poseedores de tokens JUVENTUD',
    'news.no-recent': 'No hay noticias recientes',
    
    // Real Estate
    'realestate.title': 'Portafolio inmobiliario',
    'realestate.description': 'Descubre nuestros proyectos inmobiliarios exclusivos disponibles para afiliados AFJP Cripto. Accede a propiedades con beneficios especiales y opciones de pago usando tus tokens.',
    'realestate.exclusive-benefits': 'Beneficios exclusivos para afiliados',
    'realestate.as-affiliate': 'Como afiliado AFJP Cripto, tienes acceso a beneficios especiales en nuestro portafolio inmobiliario',
    'realestate.exclusive': 'Exclusivo',
    'realestate.discount-25': '25% de descuento',
    'realestate.discount-desc': 'Descuento especial en tarifas de alquiler para todos los afiliados AFJP Cripto',
    'realestate.juventud-25': 'Pago con JUVENTUD',
    'realestate.juventud-desc': 'Alquila propiedades pagando directamente con tokens JUVENTUD',
    'realestate.ladrillo-25': 'Compra con LADRILLO',
    'realestate.ladrillo-desc': 'Compra propiedades usando tokens LADRILLO para inversiones inmobiliarias',
    'realestate.special-financing': 'Financiamiento especial',
    'realestate.financing-desc': 'Opciones de pago flexibles y términos preferenciales',
    'realestate.available-projects': 'Proyectos disponibles',
    'realestate.torres-puerto': 'Torres de Aptos',
    'realestate.torres-location': 'Puerto Madero, Buenos Aires',
    'realestate.apartments': 'Departamentos',
    'realestate.under-construction': 'En construcción',
    'realestate.completed': 'Completado',
    'realestate.pre-sale': 'Pre-venta',
    'realestate.express-interest': 'Expresar interés',
    'realestate.interest-form-desc': 'Dejá tu información y te contactaremos con ofertas personalizadas.',
    'realestate.projects': 'Proyectos',
    'realestate.projects-desc': 'Invierte con tokens LADRILLO en futuros proyectos inmobiliarios y apoya su desarrollo desde el inicio',
    'realestate.investment': 'Inversión en Proyectos Futuros',
    'realestate.investment-desc': 'Usa tus tokens LADRILLO para financiar y apoyar el desarrollo de nuevos proyectos inmobiliarios',
    'realestate.finance': 'Financiamiento Directo',
    'realestate.finance-desc': 'Contribuye directamente al desarrollo de proyectos usando tokens LADRILLO',
    'realestate.returns': 'Retornos Atractivos',
    'realestate.returns-desc': 'Obtén retornos estimados entre 10% y 15% anual al completarse los proyectos',

    // Form translations
    'form.name-required': 'El nombre es requerido',
    'form.invalid-email': 'Por favor ingresa un email válido',
    'form.invalid-phone': 'Por favor ingresa un teléfono válido',
    'form.select-interest': 'Por favor selecciona tu interés',
    'form.sent-title': '¡Formulario enviado!',
    'form.sent-desc': 'Te contactaremos pronto con más información.',
    'form.full-name': 'Nombre completo',
    'form.your-name': 'Tu nombre',
    'form.email': 'Email',
    'form.phone': 'Teléfono',
    'form.interested-in': 'Estoy interesado en:',
    'form.rent-property': 'Alquilar una propiedad',
    'form.buy-property': 'Comprar una propiedad',
    'form.receive-info': 'Recibir información solamente',
    'form.additional-message': 'Mensaje Adicional (Opcional)',
    'form.additional-placeholder': 'Cuéntanos sobre tus necesidades específicas o preferencias...',
    'form.send-request': 'Enviar solicitud',
    
    // Footer
    'footer.links': 'Enlaces Rápidos',
    'footer.resources': 'Recursos',
    'footer.official-aptos': 'Aptos Oficial',
    'footer.documentation': 'Documentación',
    'footer.explorer': 'Explorador de Bloques',
    'footer.rights': '© 2025 AFJP Cripto. Todos los derechos reservados.',
    
    // Why Aptos Section
    'why-aptos.title': 'Por qué elegir',
    'why-aptos.subtitle': 'Descubre las ventajas de construir nuestro fondo de jubilación en el ecosistema blockchain más avanzado',
    'why-aptos.interoperability': 'Interoperabilidad',
    'why-aptos.interoperability-desc': 'Conecta con múltiples blockchains y sistemas financieros sin problemas',
    'why-aptos.scalability': 'Escalabilidad',
    'why-aptos.scalability-desc': 'Procesa miles de transacciones por segundo con tarifas mínimas',
    'why-aptos.security': 'Seguridad',
    'why-aptos.security-desc': 'Modelo de seguridad mediante criptografía',
    'why-aptos.governance': 'Gobernanza de DAO NNS',
    'why-aptos.governance-desc': 'Sistema de gobernanza democrática para actualizaciones y decisiones del protocolo',
    
    // Advantages Section
    'advantages.title': 'Ventajas competitivas',
    'advantages.subtitle': 'Por qué AFJP Cripto es la mejor opción para tu jubilación basada en blockchain',
    'advantages.dedicated-parachain': 'Blockchain optimizada',
    'advantages.dedicated-desc': 'Almacenar fotos y videos de los activos cuesta menos gracias a Aptos',
    'advantages.tokenized-assets': 'Activos reales tokenizados',
    'advantages.tokenized-desc': 'Bienes raíces y activos tradicionales representados como tokens blockchain',
    'advantages.institutional-security': 'Seguridad institucional',
    'advantages.institutional-desc': 'Seguridad a nivel bancario con transparencia blockchain',
    'advantages.continuous-evolution': 'Evolución continua',
    'advantages.continuous-desc': 'Actualizaciones y mejoras regulares sin interrupción del servicio',
    'advantages.defi-ecosystem': 'Ecosistema DeFi',
    'advantages.defi-desc': 'Acceso a herramientas de finanzas descentralizadas y oportunidades de rendimiento',
    'advantages.long-term-resistance': 'Resistencia a largo plazo',
    'advantages.long-term-desc': 'Construido para durar décadas con estándares tecnológicos en evolución',
  }
};

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<string>('es');

  const t = (key: string): string => {
    const currentTranslations = translations[language as keyof typeof translations] || translations.es;
    return currentTranslations[key as keyof typeof currentTranslations] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextProps => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
